#  Get base SDK Image from Microsoft
FROM mcr.microsoft.com/dotnet/core/sdk:5.0 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out .

FROM mcr.microsoft.com/dotnet/core/aspnet:5.0
WORKDIR /app
EXPOSE 80
COPY --from=build-env /app/out .
ENTRYPOINT ["catalog","Catalog.dll"]
